sudo: false
language: node_js
os:
  - linux
node_js:
  - '8'
cache: npm

script:
  - bash travis.sh

jobs:
  include: 
      if: (branch = gh-pages) AND (commit_message ~ /(docs)/)
      - stage: build
        script: sh doc/release.sh
      - stage: deploy
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: ./doc/noahv

notifications:
  email:
    on_success: never
    on_failure: never